FROM almalinux:8
RUN dnf install nginx -y
EXPOSE 9090 80 8080 80
LABEL course="DevOps" \
      trainer="Siva Anna" \
      time="Morning"
ENV env="dev" \
    sub="docker" \
    trainee="Siva Anna"
CMD ["sleep","1000"]