FROM almalinux:9
RUN dnf install nginx -y
CMD ["nginx","-g","dameon reload;"]
LABEL "COURSE"="DEVOPS" \
      "TRAINER"="siva ANNA" \
      "TIME"="MORNING"
EXPOSE 90 8080 80 9090
ENV "NAME"="CHANDRA" \
    "COURSE"="DEVOPS" \
    "TRAINER"="SIVA ANNA" \
    "ENVIRONMENT"="DEV"
