FROM almalinux:8
RUN dnf install nginx -y
LABEL course="devops" \
      trainer="sivaanna" \
      time="morning"
ENV COURSE='DEVOPS' \
    TRAINER='SIVA ANNA' \
    TIME='MORNING' \
    LEARNER='CHANDRA'
